/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/
module src.gui.configform;
import dfl.all;
import src.common, src.sys.config, src.gui.configpanels.base;
import voile.misc;

class ConfigForm: dfl.form.Form
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.treeview.TreeView treeConfig;
	dfl.splitter.Splitter splitter;
	dfl.panel.Panel pnlConfig;
	dfl.panel.Panel pnlConsole;
	dfl.button.Button btnOk;
	dfl.button.Button btnApply;
	dfl.button.Button btnCancel;
	dfl.panel.Panel pnlMain;
	//~Entice Designer variables end here.
	
	
	/***************************************************************************
	 * 
	 */
	Handler!(void delegate()) onConfigApplied;
	
	/***************************************************************************
	 * 
	 */
	this()
	{
		initializeConfigForm();
		
		//@  Other ConfigForm initialization code here.
		
		// デフォルトのボタン
		btnOk.notifyDefault(true);
		
		// OK時の挙動
		btnOk.click ~= (Object s, EventArgs e)
		{
			onConfigApplied();
			hide();
		};
		
		// 適用時の挙動
		btnApply.click ~= (Object s, EventArgs e)
		{
			onConfigApplied();
		};
		
		// キャンセル時の挙動
		btnCancel.click ~= (Object s, EventArgs e)
		{
			hide();
		};
		
		// 閉じられるときの挙動
		closing ~= (Object s, CancelEventArgs e)
		{
			hide();
			e.cancel = true;
		};
	}
	
	
	/***************************************************************************
	 * 
	 */
	void config(Config cfg) @property
	{
		foreach (c; pnlMain.controls)
		{
			if (auto cp = cast(ConfigPanel)c)
				cp.loadConfig(cfg);
		}
	}
	
	
	/***************************************************************************
	 * 
	 */
	Config config() @property
	{
		Config cfg;
		foreach (c; pnlMain.controls)
		{
			if (auto cp = cast(ConfigPanel)c)
				cp.applyConfig(cfg);
		}
		return cfg;
	}
	
	private void initializeConfigForm()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Form
		text = "設定";
		clientSize = dfl.all.Size(470, 411);
		//~DFL dfl.treeview.TreeView=treeConfig
		treeConfig = new dfl.treeview.TreeView();
		treeConfig.name = "treeConfig";
		treeConfig.dock = dfl.all.DockStyle.LEFT;
		treeConfig.bounds = dfl.all.Rect(0, 0, 128, 411);
		treeConfig.parent = this;
		//~DFL dfl.splitter.Splitter=splitter
		splitter = new dfl.splitter.Splitter();
		splitter.name = "splitter";
		splitter.bounds = dfl.all.Rect(128, 0, 9, 411);
		splitter.parent = this;
		//~DFL dfl.panel.Panel=pnlConfig
		pnlConfig = new dfl.panel.Panel();
		pnlConfig.name = "pnlConfig";
		pnlConfig.dock = dfl.all.DockStyle.FILL;
		pnlConfig.bounds = dfl.all.Rect(137, 0, 333, 411);
		pnlConfig.parent = this;
		//~DFL dfl.panel.Panel=pnlConsole
		pnlConsole = new dfl.panel.Panel();
		pnlConsole.name = "pnlConsole";
		pnlConsole.dock = dfl.all.DockStyle.BOTTOM;
		pnlConsole.bounds = dfl.all.Rect(0, 366, 333, 45);
		pnlConsole.parent = pnlConfig;
		//~DFL dfl.button.Button=btnOk
		btnOk = new dfl.button.Button();
		btnOk.name = "btnOk";
		btnOk.text = "OK";
		btnOk.bounds = dfl.all.Rect(16, 16, 96, 24);
		btnOk.parent = pnlConsole;
		//~DFL dfl.button.Button=btnApply
		btnApply = new dfl.button.Button();
		btnApply.name = "btnApply";
		btnApply.text = "適用";
		btnApply.bounds = dfl.all.Rect(120, 16, 96, 24);
		btnApply.parent = pnlConsole;
		//~DFL dfl.button.Button=btnCancel
		btnCancel = new dfl.button.Button();
		btnCancel.name = "btnCancel";
		btnCancel.text = "キャンセル";
		btnCancel.bounds = dfl.all.Rect(224, 16, 96, 24);
		btnCancel.parent = pnlConsole;
		//~DFL dfl.panel.Panel=pnlMain
		pnlMain = new dfl.panel.Panel();
		pnlMain.name = "pnlMain";
		pnlMain.dock = dfl.all.DockStyle.FILL;
		pnlMain.bounds = dfl.all.Rect(0, 0, 333, 366);
		pnlMain.parent = pnlConfig;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

