/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/
module src.gui.controlpanel;

import dfl.all;


class ControlPanel: dfl.panel.Panel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.panel.Panel panel1;
	dfl.button.Button btnPush;
	dfl.button.Button btnPop;
	//~Entice Designer variables end here.
	
	
	this()
	{
		initializeControlPanel();
		
		//@  Other ControlPanel initialization code here.
		with (dockPadding)
		{
			left   = 10;
			top    = 4;
			right  = 10;
			bottom = 4;
		}
	}
	
	
	private void initializeControlPanel()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Panel
		name = "ControlPanel";
		bounds = dfl.all.Rect(0, 0, 200, 32);
		//~DFL dfl.panel.Panel=panel1
		panel1 = new dfl.panel.Panel();
		panel1.name = "panel1";
		panel1.dock = dfl.all.DockStyle.LEFT;
		panel1.bounds = dfl.all.Rect(0, 0, 16, 32);
		panel1.parent = this;
		//~DFL dfl.button.Button=btnPush
		btnPush = new dfl.button.Button();
		btnPush.name = "btnPush";
		btnPush.dock = dfl.all.DockStyle.LEFT;
		btnPush.bounds = dfl.all.Rect(16, 0, 48, 32);
		btnPush.parent = this;
		//~DFL dfl.button.Button=btnPop
		btnPop = new dfl.button.Button();
		btnPop.name = "btnPop";
		btnPop.dock = dfl.all.DockStyle.LEFT;
		btnPop.bounds = dfl.all.Rect(64, 0, 48, 32);
		btnPop.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

