/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/

module src.gui.taskpanel;
import dfl.all;

/*******************************************************************************
 * 
 */
class TaskPanel: dfl.panel.Panel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.button.RadioButton radioTask;
	dfl.button.CheckBox chkToggle;
	dfl.textbox.TextBox txtDurTask;
	dfl.button.Button btnCopy;
	dfl.panel.Panel panel2;
	dfl.button.Button btnReset;
	dfl.panel.Panel panel3;
	dfl.button.Button btnRemove;
	dfl.panel.Panel panel1;
	dfl.button.Button btnConfig;
	//~Entice Designer variables end here.
	
	
	/***************************************************************************
	 * 
	 */
	void activateTask()
	{
		foreach (c; controls)
		{
			c.enabled = true;
		}
		with (dockPadding)
		{
			left   = 10;
			top    = 4;
			right  = 10;
			bottom = 4;
		}
		radioTask.checked = true;
		height = 32+4+4;
		txtDurTask.font = new dfl.all.Font(txtDurTask.font.name, 14.5);
	}
	
	
	/***************************************************************************
	 * 
	 */
	void disactivateTask()
	{
		foreach (c; controls)
		{
			if (c !is radioTask)
			{
				c.enabled = false;
			}
		}
		with (dockPadding)
		{
			left   = 10;
			top    = 2;
			right  = 10;
			bottom = 2;
		}
		radioTask.checked = false;
		height = 16+2+2;
		txtDurTask.font = new dfl.all.Font(txtDurTask.font.name, 9);
	}
	
	
	/***************************************************************************
	 * 
	 */
	this()
	{
		initializeTaskPanel();
		
		//@  Other TaskPanel initialization code here.
		with (dockPadding)
		{
			left   = 10;
			top    = 4;
			right  = 10;
			bottom = 4;
		}
		chkToggle.textAlign = ContentAlignment.MIDDLE_CENTER;
		btnReset.textAlign  = ContentAlignment.MIDDLE_CENTER;
		btnCopy.textAlign   = ContentAlignment.MIDDLE_CENTER;
		chkToggle.click ~= (Control c, EventArgs e)
		{
			if (chkToggle.checked)
			{
				chkToggle.text = "Stop";
			}
			else
			{
				chkToggle.text = "Run";
			}
		};
		
	}
	
	
	private void initializeTaskPanel()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Panel
		name = "TaskPanel";
		dock = dfl.all.DockStyle.TOP;
		bounds = dfl.all.Rect(0, 0, 448, 32);
		//~DFL dfl.button.RadioButton=radioTask
		radioTask = new dfl.button.RadioButton();
		radioTask.name = "radioTask";
		radioTask.dock = dfl.all.DockStyle.LEFT;
		radioTask.bounds = dfl.all.Rect(0, 0, 16, 32);
		radioTask.parent = this;
		//~DFL dfl.button.CheckBox=chkToggle
		chkToggle = new dfl.button.CheckBox();
		chkToggle.name = "chkToggle";
		chkToggle.dock = dfl.all.DockStyle.LEFT;
		chkToggle.text = "Stop";
		chkToggle.appearance = dfl.all.Appearance.BUTTON;
		chkToggle.checkState = dfl.all.CheckState.CHECKED;
		chkToggle.bounds = dfl.all.Rect(16, 0, 64, 32);
		chkToggle.parent = this;
		//~DFL dfl.textbox.TextBox=txtDurTask
		txtDurTask = new dfl.textbox.TextBox();
		txtDurTask.name = "txtDurTask";
		txtDurTask.dock = dfl.all.DockStyle.LEFT;
		txtDurTask.bounds = dfl.all.Rect(80, 0, 128, 32);
		txtDurTask.parent = this;
		//~DFL dfl.button.Button=btnCopy
		btnCopy = new dfl.button.Button();
		btnCopy.name = "btnCopy";
		btnCopy.dock = dfl.all.DockStyle.LEFT;
		btnCopy.text = "Copy";
		btnCopy.bounds = dfl.all.Rect(208, 0, 48, 32);
		btnCopy.parent = this;
		//~DFL dfl.panel.Panel=panel2
		panel2 = new dfl.panel.Panel();
		panel2.name = "panel2";
		panel2.dock = dfl.all.DockStyle.LEFT;
		panel2.bounds = dfl.all.Rect(256, 0, 16, 32);
		panel2.parent = this;
		//~DFL dfl.button.Button=btnReset
		btnReset = new dfl.button.Button();
		btnReset.name = "btnReset";
		btnReset.dock = dfl.all.DockStyle.LEFT;
		btnReset.text = "Reset";
		btnReset.bounds = dfl.all.Rect(272, 0, 48, 32);
		btnReset.parent = this;
		//~DFL dfl.panel.Panel=panel3
		panel3 = new dfl.panel.Panel();
		panel3.name = "panel3";
		panel3.dock = dfl.all.DockStyle.LEFT;
		panel3.bounds = dfl.all.Rect(320, 0, 16, 32);
		panel3.parent = this;
		//~DFL dfl.button.Button=btnRemove
		btnRemove = new dfl.button.Button();
		btnRemove.name = "btnRemove";
		btnRemove.dock = dfl.all.DockStyle.LEFT;
		btnRemove.text = "Del";
		btnRemove.bounds = dfl.all.Rect(336, 0, 48, 32);
		btnRemove.parent = this;
		//~DFL dfl.panel.Panel=panel1
		panel1 = new dfl.panel.Panel();
		panel1.name = "panel1";
		panel1.dock = dfl.all.DockStyle.LEFT;
		panel1.bounds = dfl.all.Rect(384, 0, 16, 32);
		panel1.parent = this;
		//~DFL dfl.button.Button=btnConfig
		btnConfig = new dfl.button.Button();
		btnConfig.name = "btnConfig";
		btnConfig.dock = dfl.all.DockStyle.LEFT;
		btnConfig.bounds = dfl.all.Rect(400, 0, 32, 32);
		btnConfig.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

