/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/
module src.gui.configpanels.copyformatsettings;
import dfl.all;

import src.gui.configpanels.base, src.sys.config;

/*******************************************************************************
 * 
 */
class CopyFormatSettings: src.gui.configpanels.base.ConfigPanel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.label.Label label1;
	dfl.textbox.TextBox txtInterrupt;
	dfl.label.Label label2;
	dfl.textbox.TextBox txtTask;
	//~Entice Designer variables end here.
	
	/***************************************************************************
	 * 
	 */
	override void applyConfig(ref Config cfg)
	{
		cfg.fmtCopyForInterrupt = txtInterrupt.text;
		cfg.fmtCopyForTask      = txtTask.text;
	}
	
	
	/***************************************************************************
	 * 
	 */
	override void loadConfig(in ref Config cfg)
	{
		txtInterrupt.text = cfg.fmtCopyForInterrupt;
		txtTask.text      = cfg.fmtCopyForTask;
	}
	
	
	/***************************************************************************
	 * 
	 */
	this()
	{
		initializeCopyFormatSettings();
		
		//@  Other CopyFormatSettings initialization code here.
		
	}
	
	
	private void initializeCopyFormatSettings()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Panel
		name = "CopyFormatSettings";
		dock = dfl.all.DockStyle.FILL;
		bounds = dfl.all.Rect(0, 0, 200, 128);
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.dock = dfl.all.DockStyle.TOP;
		label1.text = "割り込み時間のフォーマット";
		label1.textAlign = dfl.all.ContentAlignment.MIDDLE_LEFT;
		label1.bounds = dfl.all.Rect(0, 0, 200, 23);
		label1.parent = this;
		//~DFL dfl.textbox.TextBox=txtInterrupt
		txtInterrupt = new dfl.textbox.TextBox();
		txtInterrupt.name = "txtInterrupt";
		txtInterrupt.dock = dfl.all.DockStyle.TOP;
		txtInterrupt.bounds = dfl.all.Rect(0, 23, 200, 24);
		txtInterrupt.parent = this;
		//~DFL dfl.label.Label=label2
		label2 = new dfl.label.Label();
		label2.name = "label2";
		label2.dock = dfl.all.DockStyle.TOP;
		label2.text = "タスクのフォーマット";
		label2.textAlign = dfl.all.ContentAlignment.MIDDLE_LEFT;
		label2.bounds = dfl.all.Rect(0, 47, 200, 23);
		label2.parent = this;
		//~DFL dfl.textbox.TextBox=txtTask
		txtTask = new dfl.textbox.TextBox();
		txtTask.name = "txtTask";
		txtTask.dock = dfl.all.DockStyle.TOP;
		txtTask.bounds = dfl.all.Rect(0, 70, 200, 24);
		txtTask.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

