/*
	Generated by Entice Designer
	Entice Designer written by Christopher E. Miller
	www.dprogramming.com/entice.php
*/
module src.gui.configpanels.saveloadsettings;

import dfl.all;
import src.gui.configpanels.base, src.sys.config;

/*******************************************************************************
 * 
 */
class SaveLoadSettings: src.gui.configpanels.base.ConfigPanel
{
	// Do not modify or move this block of variables.
	//~Entice Designer variables begin here.
	dfl.button.CheckBox chkSaveAtExit;
	dfl.button.CheckBox chkLoadAtStart;
	dfl.textbox.TextBox txtFilename;
	dfl.button.Button btnRefFile;
	dfl.label.Label label1;
	//~Entice Designer variables end here.
	
	
	/***************************************************************************
	 * 
	 */
	override void applyConfig(ref Config cfg)
	{
		cfg.saveDataAtAppExit       = chkSaveAtExit.checked;
		cfg.loadDataAtAppStart      = chkLoadAtStart.checked;
		cfg.autoSaveAndLoadFilename = txtFilename.text;
	}
	
	
	/***************************************************************************
	 * 
	 */
	override void loadConfig(in ref Config cfg)
	{
		chkSaveAtExit.checked  = cfg.saveDataAtAppExit;
		chkLoadAtStart.checked = cfg.loadDataAtAppStart;
		txtFilename.text       = cfg.autoSaveAndLoadFilename;
	}
	
	
	/***************************************************************************
	 * 
	 */
	this()
	{
		initializeSaveLoadSettings();
		
		//@  Other SaveLoadSettings initialization code here.
		btnRefFile.click ~= (Object o, EventArgs e)
		{
			import std.file;
			auto dialog = new SaveFileDialog;
			with (dialog)
			{
				checkFileExists  = false;
				checkPathExists  = true;
				defaultExt       = ".json";
				dereferenceLinks = true;
				fileName         = "data.json";
				filter           = "*.json データファイル|*.json";
				filterIndex      = 0;
				//initialDirectory = getcwd();
				restoreDirectory = true;
				showHelp         = true;
				title            = "自動保存用のデータファイル";
				validateNames    = true;
				overwritePrompt     = true;
			}
			auto res = dialog.showDialog();
			if (res == DialogResult.OK)
			{
				txtFilename.text = dialog.fileName;
			}
		};
	}
	
	
	private void initializeSaveLoadSettings()
	{
		// Do not manually modify this function.
		//~Entice Designer 0.8.5.02 code begins here.
		//~DFL Panel
		name = "SaveLoadSettings";
		bounds = dfl.all.Rect(0, 0, 312, 184);
		//~DFL dfl.button.CheckBox=chkSaveAtExit
		chkSaveAtExit = new dfl.button.CheckBox();
		chkSaveAtExit.name = "chkSaveAtExit";
		chkSaveAtExit.text = "終了時にデータを自動保存する";
		chkSaveAtExit.bounds = dfl.all.Rect(8, 8, 256, 24);
		chkSaveAtExit.parent = this;
		//~DFL dfl.button.CheckBox=chkLoadAtStart
		chkLoadAtStart = new dfl.button.CheckBox();
		chkLoadAtStart.name = "chkLoadAtStart";
		chkLoadAtStart.text = "開始時にデータを自動読込する";
		chkLoadAtStart.bounds = dfl.all.Rect(8, 32, 256, 24);
		chkLoadAtStart.parent = this;
		//~DFL dfl.textbox.TextBox=txtFilename
		txtFilename = new dfl.textbox.TextBox();
		txtFilename.name = "txtFilename";
		txtFilename.bounds = dfl.all.Rect(8, 80, 232, 24);
		txtFilename.parent = this;
		//~DFL dfl.button.Button=btnRefFile
		btnRefFile = new dfl.button.Button();
		btnRefFile.name = "btnRefFile";
		btnRefFile.text = "…";
		btnRefFile.bounds = dfl.all.Rect(240, 80, 24, 24);
		btnRefFile.parent = this;
		//~DFL dfl.label.Label=label1
		label1 = new dfl.label.Label();
		label1.name = "label1";
		label1.text = "自動保存・読込には以下のファイルを使用";
		label1.bounds = dfl.all.Rect(8, 56, 256, 24);
		label1.parent = this;
		//~Entice Designer 0.8.5.02 code ends here.
	}
}

